### ISSUE TITLE
package doesn't respond when redirecting to single answer

### ISSUE THREAD

**Issue by HannesBuseyne** [datacamp/Rdocumentation#10]
when typing 'help(centre,ftsa)' or help(googl_auth) should get a single answer, but the package freezes.

**Comment by HannesBuseyne** [comment]
should be solved by https://github.com/datacamp/rdocumentation-app/commit/dd416c3aa109fd84d981fb052066a92eab8fb63d

**Comment by ludov04** [comment]
@HannesBuseyne, can I close this ?

**Comment by HannesBuseyne** [comment]
jup, should work now
