### ISSUE TITLE
Searching for "network" or "graph" should find the igraph package

### ISSUE THREAD

**Issue by krlmlr** [datacamp/Rdocumentation#11]
http://www.rdocumentation.org/search?q=network

Reason: Both keywords are part of the package's description (or details), and it seems to be way more popular than the "network" package which appears as top result.

CC @gaborcsardi.

**Comment by ludov04** [comment]
Hey, thanks for bringing this to us attention. This is the repo for the R package that integrates rdocumentation within RStudio. 
The repo for the web application is there:
https://github.com/datacamp/rdocumentation-app, can you repost your issue there ?
