### ISSUE TITLE
Make external links work

### ISSUE THREAD

**Issue by ludov04** [datacamp/Rdocumentation#16]
All external links are broken as we are in the helper pane and it does only allow to browse local pages.
To make it work, we could intercept the click event in js and send a command to RStudio to use `browseUrl` function of R that will open the link in the system's browser

**Comment by HannesBuseyne** [comment]
Should be solved on server :
https://github.com/datacamp/rdocumentation-app/pull/86/commits/17e01fd9cec03cf06e74af129aaba9e7947f545e
