### ISSUE TITLE
Navigation button on first link

### ISSUE THREAD

**Issue by ludov04** [datacamp/Rdocumentation#21]
Make the navigation work on the first click:
- One way to make it work would be to put a data-url attribute on the `<body>` or `<html>` tag 
Other idea are welcome :)

**Comment by HannesBuseyne** [comment]
I though about that, but it's a post request , so I would need to put the entire data for the request (which is sometimes very large) in a html tag. I was thinking more about checking when you go back to the first page and then try to reload the page or go to internal history, as I think this would reload the saved page 'index.html', which was the first page, without the ajax requests. But that's maybe not a very clean solution.

**Comment by HannesBuseyne** [comment]
https://github.com/datacamp/rdocumentation-app/pull/114/commits/2ca44fc357c4fb6fd178862cdf336d633c1d1cc6
