### ISSUE TITLE
check_package broken

### ISSUE THREAD

**Issue by ludov04** [datacamp/Rdocumentation#25]
It says I have the latest version for all packages
<img width="591" alt="screen shot 2016-08-23 at 10 54 45" src="https://cloud.githubusercontent.com/assets/1741726/17885992/0faeebee-6920-11e6-92b4-085a4fe6140d.png">

**Comment by HannesBuseyne** [comment]
do you have the latest version on staging of Rdocumentation with the adapted `check_package` function? I changed it in https://github.com/datacamp/Rdocumentation/commit/9cdd737e6c0bac696e0f9207f902881bcb0bc64d

**Comment by HannesBuseyne** [comment]
(because the install button does appear for me)
![image](https://cloud.githubusercontent.com/assets/13175185/17887351/5407fadc-6926-11e6-84fe-32953878e12b.png)

**Comment by ludov04** [comment]
Indeed, didn't had the right version, sorry about that
