### ISSUE TITLE
Button to install package

### ISSUE THREAD

**Issue by ludov04** [datacamp/Rdocumentation#3]
When we are on the viewer_pane only.
Beside the name of the package, display a button to install the latest version of the package if it is not already installed.
If it is, display a green checkmark with a green text saying "You have the latest version"

**Comment by ludov04** [comment]
When I arrive on a package page from a topic, it runs `check_package('...')` two times.
Also, green checkmark does not seem to appear :/

**Comment by HannesBuseyne** [comment]
do you get a javascript error of some sort? because when I run it, (with the version on staging and not on local server) it runs one time and the checkmark does appear?

**Comment by HannesBuseyne** [comment]
works for me, but if you already start typing in another command while the page is not loaded yet, it keeps executing the check_package command and can't capture the result, so I still need to solve that
