### ISSUE TITLE
R Studio keeps crashing when loaded

### ISSUE THREAD

**Issue by pgensler** [datacamp/RDocumentation#31]
RStudio keeps crashing when I try to use this package inside of RStudio 0.99.1294. I received this error as well:

Session Info:
sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1
![2016-08-31_18-07-04]
(https://cloud.githubusercontent.com/assets/7308115/18149496/fb9b7974-6fa5-11e6-91e0-65d69d4fa502.png)

**Comment by HannesBuseyne** [comment]
Hello,

Thank you for your feedback. Could you please install the newest version and try if this issue persists? (the loading procedure changed). Also, did you change any specific options for installing,such as the installation folder,... ? Because I could not recreate the problem with my setup.
