### ISSUE TITLE
API Documentation Keeps Fixed on screen

### ISSUE THREAD

**Issue by martijnsublime** [datacamp/RDocumentation#35]
See: https://www.dropbox.com/s/3bqdu8dc9f6c3as/Screenshot%202016-09-10%2010.09.49.png?dl=0 in finance top ranking

**Comment by HannesBuseyne** [comment]
Think @louisdelanoeye already fixed this in a pull request : https://github.com/datacamp/rdocumentation-app/pull/251

**Comment by filipsch** [comment]
@ludov04 I cannot reproduce; can you close if no longer relevant?
