### ISSUE TITLE
Rdocumentation Cran

### ISSUE THREAD

**Issue by martijnsublime** [datacamp/RDocumentation#36]
When on cran, the url should point to rdocumentation.org to get additional SEO value. See e.g. what was done for datacamp: https://www.dropbox.com/s/0tfg0yvd54fe5xh/Screenshot%202016-09-13%2018.57.09.png?dl=0

**Comment by ludov04** [comment]
fixed, see https://cran.r-project.org/web/packages/RDocumentation/index.html
