### ISSUE TITLE
Support Bioc release and devel

### ISSUE THREAD

**Issue by lgatto** [datacamp/RDocumentation#37]
It would be great to have the release and devel version of packages available. For example

* devel: http://bioconductor.org/packages/devel/bioc/html/Biobase.html
* release: http://bioconductor.org/packages/release/bioc/html/Biobase.html

The reason for this is that when I implement a new function and/or update the vignette with a new section, I often would like to write about and link to it. Once the devel is bumped to release, I will generally have something different on my plate and won't remember to update whatever I did a couple of months ago. 

See [version numbering](http://bioconductor.org/developers/how-to/version-numbering/) for details about versions. Feel free to ask for details.

**Comment by filipsch** [comment]
Hi @lgatto, this is an issue for the repository `datacamp/RDocumentation-app`, so I'll close this one and reopen it there; i'll make sure to tag you. 
Thanks for raising it!
