### ISSUE TITLE
unclear how to reverse the makeDefault

### ISSUE THREAD

**Issue by nickreich** [datacamp/RDocumentation#39]
I used the makeDefault to switch the default help files to be Rdocumentation, but it isn't working out for me in two scenarios and I'd like to switch back. I switched back by uninstalling the RDocumentation package, but I thought I remember it saying that I could switch back more gracefully. (and now I'm getting an error message when starting R saying that it can't find the RDocumentation package because it is in the packages loaded upon start.) The two scenarios where the help wasn't working the way I wanted it to were:

- when I tried to load up documentation when I wasn't connected to the internet: nothing showed up.
- when I tried to load up documentation for a package that I had installed locally. The help files exist but just not on RDocumentation.org.

**Comment by filipsch** [comment]
@nickreich thanks for the suggestions/

- We'll make a `undeDefault()` function or something similar.
- We'll look into the issues you mention.

For now: to get rid of the error message, go to the `.Rprofile` file in your home directory, and remove the line that tries to load the `RDocumentation` package.

Sorry for the inconvenience.

**Comment by ludov04** [comment]
@nickreich This is fixed and there is now 4 functions that you can use to have more control and granularity about what the package does.
- `disable_autoload()`
- `disable_override()`
- `enable_autoload()`
- `enable_override()`

This is in the latest version `0.7` that is not yet on CRAN but should be there soon.
In the meantime you can install the latest version using devtools.
