### ISSUE TITLE
Fallback on original function.

### ISSUE THREAD

**Issue by ludov04** [datacamp/Rdocumentation#4]
In case of problem (Rdocs down, no internet, bad error code, ...)
We have to fallback on the original function to not leave the user without documentation

**Comment by ludov04** [comment]
@HannesBuseyne  can you reference the commit fixing this by commenting on this issue.
Tip for further issues, when commenting the commit, put the number of the issue like this:
"#4" and it will automatically create a reference here to your commit

**Comment by HannesBuseyne** [comment]
This should be it :
https://github.com/datacamp/Rdocumentation/commit/f8ce2146e37dc4e422f26829c27cf27379de5e60
