### ISSUE TITLE
SEO Optimizations 

### ISSUE THREAD

**Issue by martijnsublime** [datacamp/RDocumentation#41]
Some SEO improvements that could be done:

- Add alt tag to image (use h1 value as text input) https://www.dropbox.com/s/39j5h4f8en9mhee/Screenshot%202016-09-25%2017.24.53.png?dl=0
- Put Author Name in Title: https://www.rdocumentation.org/collaborators/name/Winston%20Chang
- There seems to be 404 pages: https://www.rdocumentation.org/collaborators/524149 that are indexed by google https://www.dropbox.com/s/likhuyg26lhrhin/Screenshot%202016-09-25%2019.02.48.png?dl=0
- Author page does not have meta description with name of author in https://www.rdocumentation.org/collaborators/name/Winston%20Chang
- Task Views Page: No unique title per task view: e.g.  https://www.rdocumentation.org/taskviews#ChemPhys and https://www.rdocumentation.org/taskviews#ClinicalTrials have same title. E.g. consider changing tittle to "R Task Views: Clinical Trials" (same for H1)

**Comment by filipsch** [comment]
Closing this issue and moving it to RDocumentation-app
