### ISSUE TITLE
Remove ability to submit placeholder example

### ISSUE THREAD

**Issue by eliaseythorsson** [datacamp/RDocumentation#45]
Pressing the button "Submit your example" when no text has been entered submits the unchanged placeholder markdown text as an example. See my user generated example for group_size in the dplyr package as proof.

**Comment by ludov04** [comment]
Hi thanks for raising this issue. 
However, this is the repo hosting the RDocumentation package, for the web application, go to:
https://github.com/datacamp/RDocumentation-app
I resubmitted this issue in the correct repo, you can see it here
https://github.com/datacamp/RDocumentation-app/issues/270
