### ISSUE TITLE
Not able to delete example within RDocumentation package

### ISSUE THREAD

**Issue by eliaseythorsson** [datacamp/RDocumentation#46]
I was not able to delete my own example within the RDocumentation package. The option is available to me within Rstudio. If I press it nothing happens. If I then refresh it, the example remains but now I have no option to edit or delete the example as if I was not the author. 

I can then move over to RDocumentation.org, open the function there and it is still available in the database. There I am able to edit or delete again, and once I do so the example disappears both from RDocumentation.org and the RDocumentation package. 

I did this on the group_size() function within the dplyr package documentation, but obviously the example is no longer there.

**Comment by ludov04** [comment]
Thanks for raising this issue.
As a workaround for now, you can indeed delete or edit your example in the browser.
We'll look into that

**Comment by filipsch** [comment]
Hey @eliaseythorsson, we can't seem to reproduce this issue. It is possible that this automagically fixed itself because of other fixes we did.
Can you check again and explain step by step how you got the unwanted behavior?
