### ISSUE TITLE
RDocumentation does not work anymore

### ISSUE THREAD

**Issue by acontent** [datacamp/RDocumentation#53]
I get this error message : 
> help("c")
<simpleError in file(con, "wb"): cannot open the connection>
Warning message:
In file(con, "wb") :
  cannot open file '/Builds/CRAN-QA-Simon/packages/mavericks-x86_64/Rlib/3.3/RDocumentation/doc/index.html': No such file or directory

**Comment by ludov04** [comment]
Hi thanks for raising this issue, I have a few questions that might us solving this:

- When you say "does not work anymore", do you mean it worked for you before ? Did anything changed between the moment it worked and the moment it didn't (for example an update of R or RStudio) ?
- On which operating system are you ? 
- Do you use RDocumentation on RStudio Desktop, RStudio Server or R standalone ? 
- Which version of R/RStudio/RStudio Server do you use ?

Thanks

**Comment by acontent** [comment]
Hi,
Sorry for the lack of details - I am using RStudio-Desktop (1.0.44) or recent previews on macOS 10.11.6 

Unfortunately I can't say exactly what changed - I installed Rdoc a few days ago when it was announced in R-bloggers, used it a few times without problems and discovered this weekend that it did not work anymore. It seems a bit unlikely though that it has been caused by some change on my side because I am seeing the same message on my laptop and desktop computer.

Happy to help if I can.

**Comment by filipsch** [comment]
@ludov04 the error seems to suggest that R looks for the file `doc/index.html`. However, inside the `view_help()` function, this directory is always being created before the response of the POST request is being written into the `index.html` file there.

@acontent can you try simply re-installing the latest version of the package? This might reset the access rights to the files inside the package directory, maybe that fixes it.

```R
library(devtools)
install_github("datacamp/RDocumentation")
```

**Comment by acontent** [comment]
Hi, 

indeed, the github version seems to work fine,  whereas the CRAN version does not. Thanks !

**Comment by acontent** [comment]
Hi, 

indeed, the github version seems to work fine,  whereas the CRAN version does not. Thanks !

**Comment by filipsch** [comment]
@acontent and this also shows your help files inside an RDocumentation view inside RStudio, right? Not the original documentation? Just to double check!

**Comment by acontent** [comment]
Yes absolutely - with the latest version I get the Rdoc view inside Rstudio. With the cran version, I always get the same msg and help gets back to the standard docs.

**Comment by filipsch** [comment]
@acontent the strange bug has been fixed! Thanks for raising it!
