### ISSUE TITLE
Removing RDocumentation from RStudio

### ISSUE THREAD

**Issue by ProfFancyPants** [datacamp/RDocumentation#54]
I wanted to remove RD from RStudio. I tried to do it in the standard way using remove.packages(), however, I keep getting the message below whenever I start Rstudio. 
```
Type 'q()' to quit R.

During startup - Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘RDocumentation’
2: package ‘RDocumentation’ in options("defaultPackages") was not found 
```
Any ideas as to why this is happening?

**Comment by filipsch** [comment]
@ProfFancyPants you can open up `.Rprofile` file in your home directory, and then remove the line that loads `RDocumentation`. Sorry for the inconvenience. I'll make an issue that only loads `RDocumentation` if it's actually installed (using `require` instead of `library`).

Thanks for raising this!

**Comment by pat-s** [comment]
@filipsch Just tried your solution with `.Rprofile`. However I still get the following error message when kniting an Rmarkdown document

```
Quitting from lines 29-33 (sperrorest-vignette.Rmd) 
Error in library(p, character.only = TRUE) : 
  there is no package called 'RDocumentation'
Calls: <Anonymous> ... suppressPackageStartupMessages -> withCallingHandlers -> library
```

The code chunk consists of `library` calls. 
`RDocumentation` is not installed, I removed the line in `.Rprofile` and restarted R.

**Comment by filipsch** [comment]
@pat-s, wow, it looks like there's fancy stuff going on. Maybe your default `.RProfile` file is located somewhere else, or you have two of the. In RDocs, the location of the file is determined as:

```R
file.path(Sys.getenv("HOME"), ".Rprofile")
```

Does emptying the file that path help?

Sorry for the inconvenience this is causing!

**Comment by ymbouamboua** [comment]
Hi, i'm Yvon, a beginner in R. I have a same problem with biomaRt package:

Error in library(p, character.only = TRUE) : 
  there is no package called 'biomaRt'
Calls: <Anonymous> ... suppressPackageStartupMessages -> withCallingHandlers -> library
Exécution arrêtée

I used file.path(Sys.getenv("HOME"), ".Rprofile") and the R consol displayed                                        
> file.path(Sys.getenv("HOME"), ".Rprofile")
[1] "/Users/yvonfrid/.Rprofile"

I don't have how to access in .Rprofile.
Thank you for your help

Yvon

**Comment by filipsch** [comment]
If you install the latest version of the RDocumentation package that is on Github you should be golden. We will do a CRAN release soon!
