### ISSUE TITLE
RDocumentation Help Panel: present manual for the installed version of the package if it's higher than CRAN release

### ISSUE THREAD

**Issue by MarcinKosinski** [datacamp/RDocumentation#57]
I am using LDAvis ver 0.3.3 which is different from version 0.3.2 and has many additional parameters in main funciton.

I can onsly select manual page for LDAvis for ver 0.3.2 and 0.2 even thought I have 0.3.3 installed. 

Can you please debug/fix?

![version](https://cloud.githubusercontent.com/assets/6773454/20393813/8b4d622a-acdd-11e6-8f3b-e450149cbdf4.png)

**Comment by filipsch** [comment]
It appears that the `LDAvis` version on GitHub is `v0.3.3`, and the on on CRAN is `v0.3.2`. If the package is both on CRAN and on GitHub, RDocs' workers will parse the last version of the CRAN package and will not look at GitHub.

**Comment by MarcinKosinski** [comment]
Does it make sense? Shouldn't it look at my desktop and let me check the documentation of a package that I have installed regarding from GitHub and CRAN?

**Comment by filipsch** [comment]
@MarcinKosinski That would make more sense, indeed. It requires significant changes to both the R package as the Node application and workers that fetch and parse all the docs, so we'll have to see when we can work on this!

**Comment by MarcinKosinski** [comment]
Ok thanks. So far this is the main reason I am not using RDocumentation in
the Help Panel.
Good luck and keep going with the great work that you have done here : )

2016-11-17 18:26 GMT+01:00 Filip Schouwenaars <notifications@github.com>:
