### ISSUE TITLE
How to remo RDocumentation from my RStudio

### ISSUE THREAD

**Issue by MarcinKosinski** [datacamp/RDocumentation#58]
During installation I have agreed to open RDocumentation in my Help window in RStudio by default. How to remove this feature? I don't want RDocumentation anymore

**Comment by filipsch** [comment]
@MarcinKosinski You can use the functions

```R
disable_override() # ask for help will show standard documentation
disable_autoload() # you don't auto-load RDocumentation when you start R
```

**Comment by MarcinKosinski** [comment]
Can you extend README with that extra info? Thanks, the website is powerful but the Help Panel didn't work for me.

**Comment by filipsch** [comment]
I will!
