### ISSUE TITLE
Color of links and text of RDocumentation Help Panel in RStudio

### ISSUE THREAD

**Issue by MarcinKosinski** [datacamp/RDocumentation#59]
The text and links are too bright. I don't see anything and that is why it is hard to work with this panel.
Is there a way to change the text color and links color, so that they could be the same as text color in the R console? 

![version](https://cloud.githubusercontent.com/assets/6773454/20393873/da51c5f0-acdd-11e6-9d80-65c6be5d9276.png)

**Comment by ludov04** [comment]
The font-size and font-weight are now bigger, should be easier to read
