### ISSUE TITLE
How to view package index in RDocumentation panel?

### ISSUE THREAD

**Issue by MarcinKosinski** [datacamp/RDocumentation#60]
In base R `help(p="package")` viewed the index of a package. How this can be done in RDocumentation in RStudio? Now I run the following code and have empty panel, so I just click backwards/back arrow in help panel in RStudio to view the index in base help which is annoying.

![view_package_index](https://cloud.githubusercontent.com/assets/6773454/20394201/01bc92c2-acdf-11e6-819e-474843f3e22b.png)

**Comment by filipsch** [comment]
This should be fixed now!
