### ISSUE TITLE
Latest CRAN version of package masked by earlier one

### ISSUE THREAD

**Issue by kingaa** [datacamp/RDocumentation#63]
Package **pomp** is in [version 1.10 on CRAN](https://cran.r-project.org/package=pomp), yet the default [RDocumentation link](http://www.rdocumentation.org/packages/pomp) is to 1.4.1.1.  One can bypass this, of course, by explicitly giving the desired version number (&agrave; la https://www.rdocumentation.org/packages/pomp/versions/1.10) , but shouldn't the default be to the latest version?  This seems like a bug.

**Comment by ludov04** [comment]
Seems like a bug indeed, it seems that the package uses different versioning scheme `1.4.1.1`, `1.10`, `0.65-1`, ... and this may confuse the sorting. I'll see what I can do about that, thanks for raising.

**Comment by kingaa** [comment]
Yes, sorry about that.  For what it's worth, I think I've settled on a rational scheme for version numbering at last.  Better late than never!

**Comment by kingaa** [comment]
If you point me toward the piece of code that sorts the CRAN versions, I can attempt a pull request to fix this problem.

**Comment by filipsch** [comment]
@kingaa, it's on https://github.com/datacamp/RDocumentation-app.
The logic is in `api/models/PackageVersion.js`, if I'm not mistaken.

**Comment by kingaa** [comment]
Thanks.  I notice lines 138-144 of `api/models/PackageVersion.js`:
```
        getLatestVersion:function(packageName){
        return PackageVersion.findOne({
          where:{package_name:packageName},
          order: [[sequelize.fn('ORDER_VERSION', sequelize.col('PackageVersion.version')), 'DESC' ]]
        });
      }
```

I was imagining that it would be a relatively simple matter of teaching **RDocumentation-app** to use the same package ordering that **R** uses, i.e., lexical ordering.  However, I don't see anywhere within the package that the ordering of version numbers is specified.  Do you know where this is done?

**Comment by ludov04** [comment]
The ordering logic has been revised, `https://www.rdocumentation.org/packages/pomp` correctly goes to the latest version
