### ISSUE TITLE
DataCamp Light on RDocumentation doesn't feature all packages

### ISSUE THREAD

**Issue by jonathancornelissen** [datacamp/RDocumentation#64]
https://www.dropbox.com/s/vya20qt8qkfg7bk/Screenshot%202017-01-02%2009.07.07.png?dl=0

**Comment by filipsch** [comment]
There are docs for libraries that are not installed on the multiplexers, so they error out when you want to experiment with them.

**Comment by filipsch** [comment]
There are several ways to solve this:

- Make one 'uber-image' that contains a bunch of R packages. RDocs knows which packages are installed on this image and only enables datacamp light for a doc page if the package is available.
- Make several 'task view images', that contain R packages related to a specific field. RDocs which packages are installed on which packages, and enables datacamp light with a specific image for a doc page if the package is available.

I prefer the second option. These 'task view images' are something we could make available easily through standalone DataCamp Light as well at some point (people could easily reference which task view image they want to use in their tutorials).

**Comment by filipsch** [comment]
At second thought, for now, I want to simply disable DataCamp light on RDocs. It will be extremely difficult to feature different versions of different packages, depending on which page people are visiting, etc. 
Now, the experience is not good, and to make the experience acceptable, there's weeks of engineering to be done. So I suggest to simply fall back to non-executable code chunks.

**Comment by ludov04** [comment]
Will be resolved by https://github.com/datacamp/RDocumentation-app/issues/302
