### ISSUE TITLE
Support for jennybc/reprex in RDocs

### ISSUE THREAD

**Issue by filipsch** [datacamp/RDocumentation#65]
Suggestion by @richierocks: Jenny bryan has been working on an easy way to create reproducible examples. You can create GitHub- or StackOverflow-flavored markdown chunks that you can easily include in an issue or question. https://github.com/jennybc/reprex

We should research whether one of the currently generated markdown formats are compitable with the markdown format that RDocs uses. If yes, great, and ask Jenny that she can include it as a supported platform. If not, suggest an additional markdown flavor to the reprex repo so it is supported.

**Comment by ludov04** [comment]
After trying to understand what reprex do, more closely, I'm not completely sure what to do here.
RDocumentation uses github flavored markdown, so it's already supported if people uses `"gh"` as a venue in reprex

**Comment by richierocks** [comment]
@ludov04 

That's useful to know; it wasn't clear to me what flavor of markdown was being used in RDocumentation examples. In that case this probably just needs documenting.

I suggest changing the advice text in RDocumentation example code blocks from

> Use markdown to format your example

to

> Use github-flavored markdown to format your example

Then, optionally, offer an update to the jennybc/reprex README to say that `venue = "gh"` should be used for creating DataCamp examples.

**Comment by filipsch** [comment]
Issue moved to [datacamp/RDocumentation-app #336](https://github.com/datacamp/RDocumentation-app/issues/336) via [**ZenHub**](https://www.zenhub.com/)
