### ISSUE TITLE
Failing to parse "Format" section from CRAN

### ISSUE THREAD

**Issue by tommyjee** [datacamp/RDocumentation#67]
(cc @ncarchedi) While looking up the documentation for the `openintro::email` dataset, I noticed the descriptions of its variables, which exist on CRAN, are absent from [DataCamp's RDocumentation](https://www.rdocumentation.org/packages/openintro/versions/1.4/topics/email). AFAIK, RDocumentation is failing to parse the "Format" section on CRAN. This is highly relevant for some courses on DataCamp.

The RDocumentation shows:
![unspecified-15](https://cloud.githubusercontent.com/assets/8116732/22255190/92632910-e224-11e6-9b85-22d71ebdfe9f.png)

while CRAN shows:
![unspecified-14](https://cloud.githubusercontent.com/assets/8116732/22255077/42d1355e-e224-11e6-8d07-0b80480ca159.png)
(after "Format" section)
![unspecified-16](https://cloud.githubusercontent.com/assets/8116732/22255291/f2bf212e-e224-11e6-9b46-d9568501344f.png)

**Comment by ludov04** [comment]
related to this issue, should be fixed in the coming week. https://github.com/datacamp/RDocumentation-app/issues/289

**Comment by ludov04** [comment]
`Format` section is back
