### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ludov04** [datacamp/Rdocumentation#7]
Tests and integration with travis

**Comment by ludov04** [comment]
@HannesBuseyne is there still work to do here ?

**Comment by HannesBuseyne** [comment]
I'll have to change it, because I'll recreate the check_package function 
I'll recheck the rest of the functions, but I can't test a lot of things, because there's not a lot of output or results, everything appears in the viewerpane and that's state that I can not test

**Comment by HannesBuseyne** [comment]
https://github.com/datacamp/Rdocumentation/commit/ac1de5beb87205ba03043982885367aee08d0a55
&
https://github.com/datacamp/Rdocumentation/commit/9cdd737e6c0bac696e0f9207f902881bcb0bc64d
