### ISSUE TITLE
Missing topics and wrong links

### ISSUE THREAD

**Issue by flying-sheep** [datacamp/RDocumentation#70]
My [destiny](https://www.rdocumentation.org/packages/destiny/versions/2.0.3) package contains two main classes, which share a help topic with their creating function:

* DPT/DPT-class
* DiffusionMap/DiffusionMap class

but those topics aren’t available in the index and don’t seem to be on the site at all.

clicking a link that should lead to them leads to some random other package: https://www.rdocumentation.org/link/DPT?package=destiny&version=2.0.3

**Comment by filipsch** [comment]
Moving this bug to RDocumentation-app

**Comment by filipsch** [comment]
Issue moved to [datacamp/RDocumentation-app #314](https://github.com/datacamp/RDocumentation-app/issues/314) via [**ZenHub**](https://www.zenhub.com/)

**Comment by flying-sheep** [comment]
ag sorry for posting it wrong
