### ISSUE TITLE
 https://www.rdocumentation.org/ site does not have a current package list update..

### ISSUE THREAD

**Issue by AndreMikulec** [datacamp/RDocumentation#71]
Again, the https://www.rdocumentation.org/ site does not have a current package list update..

Right now the time is Thu Apr 06 19:21 Eastern time.

Newest packages 
ggspatial	Sun Apr 02 2017 06:31:40
net.security	Sat Apr 01 2017 16:32:06

**Comment by ludov04** [comment]
This is fixed, RDocumentation is up-to-date and crawling, thanks again for the report
