### ISSUE TITLE
lost paragraphs format in some documentation

### ISSUE THREAD

**Issue by xhdong-umd** [datacamp/RDocumentation#72]
For example, [this page](https://www.rdocumentation.org/packages/base/versions/3.3.3/topics/Extremes) have all the contents in `Details` in one paragraph, while it have 8 paragraphs in `?min` of RStudio.

**Comment by filipsch** [comment]
@xhdong-umd thanks for raising.
This is indeed different from [what you'd get traditionally from R](https://www.dropbox.com/s/5tqcz81mq50907f/Screenshot%202017-04-11%2016.37.30.png?dl=0). We'll look into it.

**Comment by ludov04** [comment]
@xhdong-umd the details section of `?min` has now the correct format:
https://www.rdocumentation.org/packages/base/versions/3.3.3/topics/Extremes
https://www.rdocumentation.org/packages/base/versions/3.4.0/topics/Extremes

**Comment by xhdong-umd** [comment]
It's much easier to read now. Thanks!
