### ISSUE TITLE
usage box appears to only be single line

### ISSUE THREAD

**Issue by machow** [datacamp/RDocumentation#73]
I was looking at `?rotations` in the GPArotation library. Although the usage section is many lines, it appears to be rendered as a single line in Rdocumentation:

![image](https://cloud.githubusercontent.com/assets/2574498/26063966/8f9a7c2a-395d-11e7-83eb-50d445daa478.png)

see here:

https://www.rdocumentation.org/packages/GPArotation/versions/2014.11-1/topics/rotations

**Comment by ludov04** [comment]
Resubmitted it to the new parser, it's better but still not nice.
Tables especially looks very bad (actually it's not displayed as a table)
Concurrent site looks better than us https://rdrr.io/cran/GPArotation/man/rotations.html

**Comment by filipsch** [comment]
Moving to `rdocumentation-app`. @machow make sure to raise issues with the app on that repo.

**Comment by filipsch** [comment]
Issue moved to [datacamp/RDocumentation-app #337](https://github.com/datacamp/RDocumentation-app/issues/337) via [**ZenHub**](https://www.zenhub.com/)
