### ISSUE TITLE
Consultation: Considering weights of species in PD score

### ISSUE THREAD

**Issue by halabikeren** [datacamp/RDocumentation#74]
Hello,

I was wondering if maybe you could help me with an issue I've encountered while attempting to consider species weights in "weighted PD" calculations.

I have a phylogenetic tree and a weights function that maps a weight to each taxon in the tree.

I would like to create a combination of the PD scores and the weights of the chosen taxa.

I tried using the linear combination a*PD(S) +weights(S) suggested [here](https://academic.oup.com/sysbio/article-lookup/doi/10.1080/10635150590947023). Unfortunately, while I can use the "a" parameter to somewhat control the significance of each element in the suggested formula, I cannot use this formulation to "standardize" the difference of the orders of magnitude of both functions: the PD and the weights function). For example, if the summations of weights of different subsets of taxa are closer to one another than their PD scores, the PD element would still end up having a higher significance in the choice of the subset than the weights.

I would like to overcome this difference in the orders of magnitude of both functions.

Do you have any suggestion regarding standardization of the orders of magnitude of the weights function?

Thanks in advance!

**Comment by filipsch** [comment]
Hi @halabikeren; unfortunately we are no specialists in the things you are describing. RDocumentation.org is an online service that groups all documentation, but we don't necessarily know the subjects of all the packages on there.
I suggest you consult other, more appropriate forums with your question.
Closing this issue.
