### ISSUE TITLE
File names should use rdname, not \name{}

### ISSUE THREAD

**Issue by hadley** [datacamp/RDocumentation#76]
e.g. https://www.rdocumentation.org/packages/magrittr/versions/1.5/topics/extract should be `/aliases`.  This is more consistent with what base R does, and would make my life easier when generating links to rdocumentation.org in pkgdown.

**Comment by ludov04** [comment]
Issue moved to [datacamp/RDocumentation-app #352](https://github.com/datacamp/RDocumentation-app/issues/352) via [**ZenHub**](https://www.zenhub.com/)
