### ISSUE TITLE
RStudio crash

### ISSUE THREAD

**Issue by valgur** [datacamp/RDocumentation#79]
Doing 
```r
library(rpart)
?rpart
```
hangs and crashes RStudio for me.

I am using RStudio 1.1.373 daily build on Windows 10.

**Comment by valgur** [comment]
Here's the [index.html](https://pastebin.com/ZwAqLs6X) file that is displayed when I run the above help command.

**Comment by filipsch** [comment]
The package is greatly simplified, and should work fine now!
