### ISSUE TITLE
Only search trough latest version of packages to avoid duplicate

### ISSUE THREAD

**Issue by ludov04** [datacamp/Rdocumentation#8]
When I type mean, I get all the versions of mean from base packages.
Filter the search trough topics belonging to latest versions

**Comment by HannesBuseyne** [comment]
should be solved on the server commit https://github.com/datacamp/rdocumentation-app/commit/01db7e13d473e109d7de513ff2dddf6e7fd399b3

**Comment by ludov04** [comment]
Nice that you reference the other repo commit here but beware that in the commit message, if you reference an issue, it will reference the issue of the repo in which the commit is made. 
So only reference the issue number when committing on the same repo.
