### ISSUE TITLE
rdocumentation.org is not showing new packages(anymore)

### ISSUE THREAD

**Issue by AndreMikulec** [datacamp/RDocumentation#80]
This site is not updating packages anymore
https://www.rdocumentation.org

Today is Monday, September, 25th.

Newest packages 
glassdoor	Thu Sep 14 2017 17:53:05

**Comment by AndreMikulec** [comment]
Still,
Nothing has changed.

This site is not updating packages anymore
https://www.rdocumentation.org
is still stuck at
"
Today is Monday, September, 25th.

Newest packages
glassdoor	Thu Sep 14 2017 17:53:05
"

**Comment by filipsch** [comment]
@AndreMikulec thanks for flagging this; we'll look into it as soon as we have some bandwidth.

**Comment by filipsch** [comment]
Moving this issue to the rdocumentation-app repo, as that repo hosts the code for the node app that serves rdocumentation.org.

**Comment by filipsch** [comment]
Issue moved to [datacamp/RDocumentation-app #385](https://github.com/datacamp/RDocumentation-app/issues/385) via [**ZenHub**](https://www.zenhub.com/)
