### ISSUE TITLE
Bad linking with same function name in multiple packages

### ISSUE THREAD

**Issue by richierocks** [datacamp/RDocumentation#86]
On the [`grDevices::Devices()`](https://www.rdocumentation.org/packages/grDevices/versions/3.5.0/topics/Devices) page, I clicked on the link to `grDevices::windows()`. By hovering over the link, I can see that it is supposed to take me to

https://www.rdocumentation.org/link/windows?package=grDevices&version=3.5.0

But I actually ended up at

https://www.rdocumentation.org/packages/alsace/versions/1.8.0/topics/windows

Perhaps the problem occurs because `grDevices::windows()` is only available under Microsoft Windows?

**Comment by filipsch** [comment]
Issue moved to [datacamp/RDocumentation-app #416](https://github.com/datacamp/RDocumentation-app/issues/416) via [**ZenHub**](https://www.zenhub.com/)
