### ISSUE TITLE
Reset / Change password

### ISSUE THREAD

**Issue by luisspuerto** [datacamp/RDocumentation#87]
Hi! 

How can I reset or change the password for my username on the page. 

Thanks!

**Comment by filipsch** [comment]
Issue moved to [datacamp/RDocumentation-app #417](https://github.com/datacamp/RDocumentation-app/issues/417) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sellers2** [comment]
I see a loop from app#87 to #417.   How can I change password on R Documentation.   breached account!
