### ISSUE TITLE
Feature Request, access specific elements of documentation

### ISSUE THREAD

**Issue by moodymudskipper** [datacamp/Rdocumentation#88]
The beauty of the R language comes in good part from the fact that most things are transparent, structured, and accessible. The doc seems to be an exception to this rule and is generally a mess to deal with for adhoc tasks such as lookup up a word or regex, or exctracting sections, parameter lists etc...

RDocumentation makes an excellent job of centralizing all the doc and makes it easily accessible. How nice would it be to leverage your database to be able to finally easily access the structure of the doc through an api and the appropriate wrapper package ?

Here are some use cases, about parameter names, as it's what brought me here :

Naming and defining stuff is hard, and having a hundred slightly different definitions doesn't help anyone.  I'd like to be able to :
* query the different definitions of 'sep' to choose the most common one
* query the descriptions including the term 'date' to explore what is a good name for my date object
* query the parameters named 'q' to make sure that I don't choose by mistake a parameter that has a very specific meaning in many or prominent packages,

**Comment by moodymudskipper** [comment]
Another use case would be extracting paragraphs or full pages from the doc to insert them into markdown documents.

**Comment by filipsch** [comment]
Issue moved to [datacamp/RDocumentation-app #424](https://github.com/datacamp/RDocumentation-app/issues/424) via [**ZenHub**](https://www.zenhub.com/)
