### ISSUE TITLE
`conn` argument of `lapply` doesn't appear in documentation

### ISSUE THREAD

**Issue by Hadrien-lcrx** [datacamp/Rdocumentation#89]
This may not be the wrong repo, and this may actually not be an issue. I'm not versed enough in R to judge, but I can't find much information online.

In the exercise [Import all tables](https://campus.datacamp.com/courses/importing-data-in-r-part-2/importing-data-from-databases-part-1?ex=7) from **Importing Data in R - Part 2**, on line 16, we have the following snippet:
```r
tables <- lapply(table_names, dbReadTable, conn = con)
```

However, when checking the documentation page on [rdocumentation](https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/lapply), there's no reference about a `conn` argument. On the [DBI rdocumentation page](https://www.rdocumentation.org/packages/DBI/versions/0.5-1), there's no `lapply` function, so it seems the one used in the exercise is the Base R function. The `conn` argument seems to refer to the DBI package.

This gets some students confused, is there any way to clarify this?

**Comment by filipsch** [comment]
@Hadrien-lcrx `lapply()` is a way to 'list apply' a function to a list of arguments. In this case,

```R
lapply(table_names, dbReadTable, con = con)
```

Is equivalent to:

```R
tables <- c()
for (name in table_names) {
   tables <- c(tables, dbReadTable(name, conn = con))
}
```

(similar to what a list comprehension does in Python)

`lapply()` is simply a short-hand functional way of writing this.

`lapply()` is a function from the `base` R package, and can be used on _any_ R function there is. Hence, it is normal that DBI doesn't make mention of `lapply()`, it's more of a recipe to get something done.

**Comment by Hadrien-lcrx** [comment]
My bad, thank you for the prompt reply!

**Comment by aferloni** [comment]
For other data camp users that were wondering, the quicker answer is: conn is an argument of dbReadTable, so check the corresponding documentation. It is not an argument of lapply.
