### ISSUE TITLE
Run examples bug

### ISSUE THREAD

**Issue by ludov04** [datacamp/Rdocumentation#9]
When clicking on the "Run examples" button,  we get 404 on the console because it tries to load `/javascript:;`

See 
<img width="1792" alt="screen shot 2016-08-03 at 18 25 36" src="https://cloud.githubusercontent.com/assets/1741726/17373306/dc8ef984-59a7-11e6-936b-49af079952b1.png">

**Comment by HannesBuseyne** [comment]
should be solved here: https://github.com/datacamp/rdocumentation-app/commit/8650f62ae0aef751ba574eef7d512eaa44db2f7b
