### ISSUE TITLE
hide user email in RDocument example

### ISSUE THREAD

**Issue by sylarbui** [datacamp/Rdocumentation#92]
A user just posted an example in RDocument but he doesn't want to show his email.

Link: https://www.rdocumentation.org/packages/xml2/versions/1.2.0/topics/write_xml

<img width="897" alt="screen shot 2018-11-15 at 13 07 44" src="https://user-images.githubusercontent.com/40219472/48533557-98903380-e8d7-11e8-94d8-08763176cb88.png">

For Support: https://datacamp.zendesk.com/agent/tickets/123749

**Comment by kasthynguyen** [comment]
![image](https://user-images.githubusercontent.com/23623241/50555946-b38ef980-0d05-11e9-81d7-392829706007.png)

https://datacamp.zendesk.com/agent/tickets/131204

**Comment by sylarbui** [comment]
This issue was moved to datacamp/RDocumentation-app#439
